export const childrenWords = [
    // Words Related to Children
    'underage', 'minor', 'child', 'loli', 'children', 'kid', 'young', 'girl', 'boy', 'preteen', 'prepubescent', 'Adolescent', 'schoolgirl', 'baby', 'infant', 'Newborn', 'Nursery', 'Kindergarten', 'Playgroup', 'Elementary school', 'Middle school', 'High school', 'Family', 'Sibling', 'Playground', 'Toy', 'Stroller', 'Diaper'
]

export const sexWords = [
    // Sexually Explicit Words
    'sex', 'seks', 'ahegao', 'pinup', 'ballgag', 'Playboy', 'Bimbo', 'pleasure', 'bodily fluids', 'pleasures', 'boudoir', 'rule34', 'brothel', 'seducing', 'dominatrix', 'seductive', 'erotic seductive', 'fuck', 'sensual', 'Hardcore', 'sexy', 'Hentai', 'Shag', 'horny', 'shibari', 'incest', 'Smut', 'jav', 'succubus', 'Jerk off king at pic', 'thot', 'kinbaku', 'transparent', 'legs spread', 'twerk', 'making love', 'voluptuous', 'naughty', 'wincest', 'orgy', 'Sultry', 'XXX', 'Bondage', 'Bdsm', 'Dog collar', 'Slavegirl', 'Transparent and Translucent', 'Arse', 'Labia', 'Ass', 'Mammaries', 'Human centipede', 'Badonkers', 'Minge', 'Massive chests', 'Big Ass', 'Mommy Milker', 'Booba', 'Nipple', 'Booty', 'Oppai ', 'Bosom', 'Organs', 'Breasts', 'Ovaries', 'Busty', 'Penis', 'Clunge', 'Phallus', 'Crotch', 'sexy female', 'Dick', 'Skimpy', 'Girth', 'Thick', 'Honkers', 'Vagina', 'Hooters', 'Veiny', 'Knob', 'no clothes', 'Speedo', 'au naturale', 'no shirt', 'bare chest', 'nude', 'barely dressed', 'bra', 'risqué', 'clear', 'scantily', 'clad', 'cleavage', 'stripped', 'full frontal unclothed', 'invisible clothes', 'wearing nothing', 'lingerie with no shirt', 'naked', 'without clothes on', 'negligee', 'zero clothes', 'Pornography', 'Explicit', 'Adult', 'NSFW (Not Safe For Work)', 'XXX', 'Erotic', 'Sexual', 'Sensual', 'Intimate', 'Nudity', 'Obscene', 'Vulgar', 'Graphic', 'Hardcore', 'Fetish', 'Kink', 'Erotic art', 'Erotica', 'Pornographic', 'Nude', 'Provocative', 'Lewd', 'Passionate', 'Seductive', 'X-rated', 'Adult content', 'Sexually explicit', 'Mature content', 'Adult entertainment', 'Erotic imagery', 'Desirable', 'Pleasure', 'Lust', 'Orgasm', 'Indecent', 'Raunchy', 'Steamy', 'Uncensored', 'Naughty', 'Bedroom', 'Censored', 'Bodily', 'Erogenous', 'Adult industry', 'Graphic content', 'Sensuous', 'Taboo', 'Forbidden', 'Private parts', 'Erotic literature', 'Sexual encounter', 'Intimate moment', 'Adult film', 'Provocative pose', 'Erotic scene', 'Naked', 'Swimsuit', 'Lingerie', 'Bikini', 'Underwear', 'Intercourse', 'Erogenous zones', 'Pleasure zones', 'Kinky', 'Dominatrix', 'Swingers', 'Threesome', 'Gangbang', 'BDSM', 'Escort services', 'Camgirl/Camboy', 'Virtual adult entertainment', 'Phone sex', 'Porn star', 'Pornographic materials', 'Erotic chat', 'Online dating', 'Hookup', 'Cybersex', 'Explicit language', 'Sex talk', 'Sexual innuendo', 'Condom', 'Lubricant', 'Vibrator', 'Dildo', 'Prostitution', 'Adult toys', 'Sex act names', 'blowjob', 'anal', 'doggy style', 'Sexual positions', 'Erotic massage', 'Nudist/naturist', 'Exhibitionist', 'Voyeurism', 'Adult chat', 'Online adult communities', 'Live streaming adult content', 'Erotic roleplay', 'Adult dating sites', 'Erotic', 'Sexually explicit stories', 'Nipple', 'Genitals', 'Lolicon', 'Shotacon', 'porn', 'Torture', 'Disturbing', 'Farts', 'Fart', 'Poop', 'Errect', 'Big Black', 'Voluptuous', 'Seductive', 'Sperm', 'Hot', 'Sexy', 'Sensored', 'Censored', 'Silenced', 'Deepfake', 'Inappropriate', 'Waifu', 'mp5', 'Succubus',
]

export const tabooWords = [
    // Taboo Words 
    'terrorist', 'terrorism', 'suicide', 'massacre', 'self-harm', 'self harm', 'school shooting', 'selfharm', 'overdose', 'kidnap', 'gore', 'mutilate', 'decapitate', 'bloodbath', 'slaughter', 'SSN', 'creditcard', 'passport', 'address', 'genocides', 'holocaust', 'lynchings', 'simp', 'incel', 'prophet muhammad', 'prophetmuhammad', 'nigger', 'reggin', 'coon', 'beaner', 'chink', 'chinky', 'gook', 'kike', 'japs', 'wetback', 'cooli', 'dago'
]